######################## default configuration ####################
baseURL = "/"
title = "Saasis - Hugo Saas Landing Theme"
theme = "saasis-hugo"
# post pagination
pagination.pagerSize = 6 # post per page
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # disable language from here

########################### Services #############################
[services]
[services.googleAnalytics]
ID = 'G-MEASUREMENT_ID' # see https://gohugo.io/templates/internal/#configure-google-analytics

[services.disqus]
shortname = 'themefisher-template' # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/

############################# Imaging ##############################
[imaging]
quality = 100

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[markup]
[markup.goldmark.renderer]
unsafe = true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
